### ISSUE TITLE
Enable search with minimum salary

### ISSUE THREAD

**Issue by dvbuntu** [derekevans/IndeedMap#3]
Searching on indeed.com allows specifying a minimum salary.  This would be an excellent feature to add to the map view.  Their basic web search seems to parse it automatically, but I suspect the API doesn't do this by default.

For example, when currently searching your app, querying "Data Scientist $100,000" around Pittsburgh returns zero results.  But the same query on indeed.com yields 41 jobs.

Javascript isn't my native language, else I would offer a pull request on this.  Thanks for a great tool!

**Comment by derekevans** [comment]
Hey Dan,

Glad you like the Indeed map. It shouldn’t be too difficult to add a salary search field to the app. I’ll look into this more later in the week and I’ll let you know when it’s available on the site. 

Regards, 

Derek

**Comment by derekevans** [comment]
I went ahead and added the salary field to the search.  Check it out here:
http://derekevans.herokuapp.com/jobsite

You can input salary in various formats.  For example:
$100,000
100000
$100k
$50k-$100k

If you don't want to filter by salary, you can just leave this input blank.

**Comment by dvbuntu** [comment]
You, sir, deserve a medal.  This is exactly what I've been looking for.

One oddity: searching on your map vs indeed.com seem to give slightly different results.  For example, searching "data scientist" at $100000 within 25 miles of Pittsburgh, PA returns 30 jobs on your map but 43 jobs on indeed.com.  Not a big deal, and I wouldn't be surprised if it's the nature of their API to not share all the content.

**Comment by derekevans** [comment]
Great! I’m glad this helped you out. 

I played around with the search parameters to see if I could get something that matched the number of jobs for the same search on the Indeed site but always came up with slightly fewer jobs.  I’m pretty sure it’s just the nature of the API.
